### ISSUE TITLE
Lost after rating a proposal

### ISSUE THREAD

**Issue by rukala** [liqd/euth_wagtail#199] opened 2016-08-22 08:51 UTC
After rating the Sauna proposal I was directed to an empty page (https://opin-dev.liqd.net/de/login/?next=/de/ideas/saunabesuch/) 

![bildschirmfoto 2016-08-22 um 10 50 25](https://cloud.githubusercontent.com/assets/11075214/17848878/41588990-6856-11e6-9696-7d384036ad9a.png)

**Comment by slomo** [comment] 2016-08-25 09:47
It seems you are directed to the login for some reason, which doesn't display because you are already login. Where you logged in befor clicking on rate?

Issues to fix:
  - if user is directed to login and is already login, offer a logout button and a redirect back to `next`, only redirecting might result in loops
  - why did rate redirect a logged in user to login

**Comment by NadineKarbach** [comment] 2016-09-01 15:18
@rukala @slomo i tried to reproduce the problem: i failed. I discovered however, that rating any proposal was not possible for me (both on dev and stage). I was logged in as a normal user. I tested on safari and firefox. I can rate comments though. Thanks for taking care of it

**Comment by slomo** [comment] 2016-09-27 07:27
@NadineKarbach It might be that rating was disabled. Since this ticket is quite all and the mentioned features work for me, I'll close this. If you should still have problems feel free to reopen.

**Closed by slomo** 2016-09-27 07:27 UTC
Labels: user feedback
